name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- bqplot
- ipykernel
- ipyleaflet
- ipywidgets>=7.5.0
- jupyter_sphinx
- matplotlib
- nbformat
- nbsphinx>=0.4,<0.5
- numpy
- python
- recommonmark
- sphinx>=1.4.6
- sphinx_rtd_theme
